Change implementation
Rory80Hz/rubbernecker pull request #3
Opened 2016-11-23 10:46 UTC by paroxp

## What

We may want to keep the current template of the board, which may prevent people from being lost or scroll too much.

The syntax has been somewhat cleaned up, some of the information either hidden or deleted.

Unfortunately, some javascript has been added. I am terribly sorry about that.

## How to review

Fire up the application and checkout my approach. Perhaps, ask people around for their opinion too.

Feel free, to give me a smack on the back of the head.

2016-12-14 18:23 UTC, Rory80Hz commented
Cool! I'll check it out.

2016-12-14 18:40 UTC, Rory80Hz requested changes
Looks good, just a couple of minor tweaks!

2016-12-14 18:40 UTC, Rory80Hz commented on views/index.ejs
> +            <h2>Play</h2>
Lets Label these 'Doing' 'Reviewing' 'Approving'

2016-12-14 18:40 UTC, Rory80Hz commented on views/index.ejs
> +<!-- I am terribly sorry for this... Really sorry... - Rafal -->
lol, that's fine. let's include it in source though, instead of via the CDN, add it to public/js/

2016-12-14 21:07 UTC, paroxp commented on views/index.ejs
> +            <h2>Play</h2>
Certainly.

2016-12-14 21:08 UTC, paroxp commented on views/index.ejs
> +<!-- I am terribly sorry for this... Really sorry... - Rafal -->
Sure thing :)

2016-12-20 14:02 UTC, paroxp commented
Just FYI, I did the above requested changes. Sorry, if you're waiting on me :(

2019-03-18 12:25 UTC, closed without merging